PUT http://es.testlab.local/auth?pretty
Content-Type: application/json

{
  "mappings": {
    "dynamic": "false",
    "properties": {
      "type":{
        "type": "keyword"
      },
      "id": {
        "type": "keyword"
      }
    }
  },
  "settings": {
    "index": {
      "number_of_shards": 3,
      "number_of_replicas": 0
    }
  }
}