###
GET http://127.0.0.1:8000/ping

###
GET http://127.0.0.1:8000/mypath

###
GET http://127.0.0.1:8000/users

###
GET http://127.0.0.1:8000/roles

###
POST http://127.0.0.1:8000/enroll

{
  "name": "Sean Beard",
  "email": "sean@smithvilledrones.com",
  "password": "Fatboy242!",
  "role": "admin",
  "enabled": true
}

###
POST http://127.0.0.1:8000/auth

{
  "username": "kronedev@gmail.com",
  "password": "password"
}

###
GET http://127.0.0.1:8000/users

###
GET http://127.0.0.1:8000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2OTg1MTI1OTUsInJvbGVzIjpbInN5c2FkbWluIl0sInN1YiI6Imtyb25lZGV2QGdtYWlsLmNvbSJ9.ql1I4cpXLgc6m7e8BQKiv-8EqMppU_vcU5qwSN3mLNE

###
GET http://127.0.0.1:8000/secrets/test

###
POST http://127.0.0.1:8000/init
Content-Type: application/json

{
  "role": {
    "name": "sysadmin",
    "description": "Role that is the top-level administrator for the system",
    "active": true,
    "created": 1698333640
  },
  "user": {
    "profile": {
      "address": {
        "addr1": "6146 Queenswood Lane",
        "city": "Houston",
        "state": "TX",
        "country": "USA",
        "postalcode": "77008"
      },
      "firstname": "Sean",
      "lastname": "Beard",
      "email": "kronedev@gmail.com",
      "phone": "832-647-6520"
    },
    "roles": ["sysadmin"],
    "created": 1698333640,
    "username": "kronedev@gmail.com",
    "password": "password",
    "org": "system"
  }
}