###
GET http://127.0.0.1:8000/ping

###
GET http://127.0.0.1:8000/mypath

###
POST http://127.0.0.1:8000/enroll

{
  "name": "Sean Beard",
  "email": "sean@smithvilledrones.com",
  "password": "Fatboy242!",
  "role": "admin",
  "enabled": true
}

###
POST http://127.0.0.1:8000/authenticate

{
  "username": "sean@smithvilledrones.com",
  "password": "Fatboy242!"
}