###
PUT http://es.testlab.local/authuser?pretty
Content-Type: application/json

{
  "mappings": {
    "dynamic": "false",
    "properties": {
      "userid":{
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      },
      "name": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 32
          }
        }
      }
    }
  },
  "settings": {
    "index": {
      "number_of_shards": 3,
      "number_of_replicas": 0
    }
  }
}

###
GET http://127.0.0.1:8000/ping

###
GET http://127.0.0.1:8000/mypath

###
POST http://127.0.0.1:8000/enroll

{
  "name": "Sean Beard",
  "email": "sean@smithvilledrones.com",
  "password": "Fatboy242!",
  "role": "admin",
  "enabled": true
}

###
POST http://127.0.0.1:8000/authenticate

{
  "username": "sean@smithvilledrones.com",
  "password": "Fatboy242!"
}

###
GET http://127.0.0.1:8000/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2Nzc1OTUwMTEsInJvbGUiOiJhZG1pbiIsInVzZXIiOiJzZWFuQHNtaXRodmlsbGVkcm9uZXMuY29tIn0.HdLQLVvvrCRkxiVzJO_qNt0ibxNVchgTGKn7ORDclz0

###
GET http://127.0.0.1:8000/secrets/test