version: "3.6"
services:
  proxy:
    image: registry.fhloston.home:5000/proxy-service
    container_name: proxy_service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.files.rule=Host(`proxy.seanandaj.com`)"
      - "traefik.http.routers.files.entrypoints=web"
      - "traefik.http.services.files.loadbalancer.server.port=5000"
    environment:
      PROXY_APICONF: 0.0.0.0@5000
      PROXY_LOGCONF: console@test@info
    extra_hosts:
      - "aws.testlab.local:11.0.0.1"
    networks:
      - frontend

networks:
  frontend:
    name: traefik
    external: true
