version: '3.6'
services:
  files:
    image: registry.testlab.local:5000/files-service
    container_name: files_service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.files.rule=Host(`fileservice.testlab.local`)"
      - "traefik.http.routers.files.entrypoints=web"
      - "traefik.http.services.files.loadbalancer.server.port=5000"
    extra_hosts:
      - "localstack.testlab.local:11.0.0.1"
    networks:
      - frontend

networks:
  frontend:
    name: traefik
    external: true
